name: test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install virtual env
        run: |
          pip install virtualenv
          
      - name: make test
        run: |
          make test
