name: test

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install virtual env
        run: |
          pip install virtualenv
          
      - name: make test
        run: |
          make test
